//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.PageContent.Models {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/Footer Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{FC7945C6-47D2-43A0-8045-3B96462B4CE3}", "KGWWZiY14zDx1CqLCi5qdU9in+c=", "Sitecore.Feature.PageContent")]
    public partial interface IFooterSettingsItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Copyright Test field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("copyright_test")]
        Synthesis.FieldTypes.Interfaces.IRichTextField CopyrightTest {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/Header Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{E043B173-70CF-4AA4-8AA7-C03863D9DB08}", "bcmyp1uis9VkWmGxZDE51I/lE9I=", "Sitecore.Feature.PageContent")]
    public partial interface IHeaderSettingsItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Social Links field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("social_links")]
        Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField SocialLinks {
            get;
        }
        
        /// <summary>Represents the Reference Links field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("reference_links")]
        Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField ReferenceLinks {
            get;
        }
        
        /// <summary>Represents the Primary Navigation Links field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("primary_navigation_links")]
        Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField PrimaryNavigationLinks {
            get;
        }
        
        /// <summary>Represents the Logo field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("logo")]
        Synthesis.FieldTypes.Interfaces.IImageField Logo {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/Site Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{5BE221A1-4BF0-491F-BD98-C53B3ABFD754}", "FdVDS5Sju8uPW0GVZfJW0+lLNYc=", "Sitecore.Feature.PageContent")]
    public partial interface ISiteSettingsItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/_Base Homepage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{782EEFC5-FEFE-45F6-B426-13F83CF04A49}", "i1N5PHBPSF6sbzC6bX3k/Rpr04E=", "Sitecore.Feature.PageContent")]
    public partial interface I_BaseHomepageItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem, global::Sitecore.Feature.PageContent.Models.I_BaseWebpageItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/_Base Site Root template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{FE98FA96-B717-4D81-9F09-C7255EE07023}", "SecKD03UQQFtwdsQl8MElWinNRg=", "Sitecore.Feature.PageContent")]
    public partial interface I_BaseSiteRootItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the On field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("on")]
        Synthesis.FieldTypes.Interfaces.IBooleanField On {
            get;
        }
        
        /// <summary>Represents the Scheme field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("scheme")]
        Synthesis.FieldTypes.Interfaces.ITextField Scheme {
            get;
        }
        
        /// <summary>Represents the Target Host Name field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("target_host_name")]
        Synthesis.FieldTypes.Interfaces.ITextField TargetHostName {
            get;
        }
        
        /// <summary>Represents the Language field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("language")]
        Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField Language1 {
            get;
        }
        
        /// <summary>Represents the Login Page field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("login_page")]
        Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField LoginPage {
            get;
        }
        
        /// <summary>Represents the Require Login field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("require_login")]
        Synthesis.FieldTypes.Interfaces.IBooleanField RequireLogin {
            get;
        }
        
        /// <summary>Represents the Domain field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("domain")]
        Synthesis.FieldTypes.Interfaces.ITextField Domain {
            get;
        }
        
        /// <summary>Represents the Enable Workflow field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("enable_workflow")]
        Synthesis.FieldTypes.Interfaces.IBooleanField EnableWorkflow {
            get;
        }
        
        /// <summary>Represents the Enable Preview field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("enable_preview")]
        Synthesis.FieldTypes.Interfaces.IBooleanField EnablePreview {
            get;
        }
        
        /// <summary>Represents the Allow Debug field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("allow_debug")]
        Synthesis.FieldTypes.Interfaces.IBooleanField AllowDebug {
            get;
        }
        
        /// <summary>Represents the Browser Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("browser_title")]
        Synthesis.FieldTypes.Interfaces.ITextField BrowserTitle {
            get;
        }
        
        /// <summary>Represents the Additional Attributes field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("additional_attributes")]
        Synthesis.FieldTypes.Interfaces.IDictionaryField AdditionalAttributes {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/_Base Webpage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{09314C4F-1126-4084-9212-C98C12D5264B}", "KyHjn/URE9n5MNG4mkaHZcdJKjo=", "Sitecore.Feature.PageContent")]
    public partial interface I_BaseWebpageItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.PageContent.Models.Concrete {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/Footer Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class FooterSettings : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.PageContent.Models.IFooterSettingsItem {
        
        private Synthesis.FieldTypes.RichTextField _copyrightTest;
        
        public FooterSettings(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public FooterSettings(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Footer Settings";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{FC7945C6-47D2-43A0-8045-3B96462B4CE3}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Copyright Test field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("copyright_test")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField CopyrightTest {
            get {
                if (_copyrightTest == null) {
                    _copyrightTest = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{BDE325D0-A7F8-4466-B677-AD4535C84C7B}"], "/sitecore/templates/Feature/PageContent/Footer Settings", "Copyright Test"), this.GetSearchFieldValue("copyright_test"));
                }
                return _copyrightTest;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class FooterSettingsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{FC7945C6-47D2-43A0-8045-3B96462B4CE3}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new FooterSettings(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new FooterSettings(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/Header Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class HeaderSettings : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.PageContent.Models.IHeaderSettingsItem {
        
        private Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField _socialLinks;
        
        private Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField _referenceLinks;
        
        private Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField _primaryNavigationLinks;
        
        private Synthesis.FieldTypes.ImageField _logo;
        
        public HeaderSettings(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public HeaderSettings(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Header Settings";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{E043B173-70CF-4AA4-8AA7-C03863D9DB08}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Social Links field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("social_links")]
        public Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField SocialLinks {
            get {
                if (_socialLinks == null) {
                    _socialLinks = new Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{43BB0E3E-6DEF-4BFD-9398-3BF13628592E}"], "/sitecore/templates/Feature/PageContent/Header Settings", "Social Links"), this.GetSearchFieldValue("social_links"));
                }
                return _socialLinks;
            }
        }
        
        /// <summary>Represents the Reference Links field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("reference_links")]
        public Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField ReferenceLinks {
            get {
                if (_referenceLinks == null) {
                    _referenceLinks = new Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{F117F899-7DF2-4D8C-BACB-DF2A9BA2EDE6}"], "/sitecore/templates/Feature/PageContent/Header Settings", "Reference Links"), this.GetSearchFieldValue("reference_links"));
                }
                return _referenceLinks;
            }
        }
        
        /// <summary>Represents the Primary Navigation Links field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("primary_navigation_links")]
        public Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField PrimaryNavigationLinks {
            get {
                if (_primaryNavigationLinks == null) {
                    _primaryNavigationLinks = new Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{B13D6141-24FC-4A45-BADB-E856E2ADBAB6}"], "/sitecore/templates/Feature/PageContent/Header Settings", "Primary Navigation Links"), this.GetSearchFieldValue("primary_navigation_links"));
                }
                return _primaryNavigationLinks;
            }
        }
        
        /// <summary>Represents the Logo field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("logo")]
        public Synthesis.FieldTypes.Interfaces.IImageField Logo {
            get {
                if (_logo == null) {
                    _logo = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{D75AF866-7117-4DF6-B078-EC86581AF423}"], "/sitecore/templates/Feature/PageContent/Header Settings", "Logo"), this.GetSearchFieldValue("logo"));
                }
                return _logo;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class HeaderSettingsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{E043B173-70CF-4AA4-8AA7-C03863D9DB08}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new HeaderSettings(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new HeaderSettings(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/Site Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class SiteSettings : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.PageContent.Models.ISiteSettingsItem {
        
        public SiteSettings(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public SiteSettings(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Site Settings";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{5BE221A1-4BF0-491F-BD98-C53B3ABFD754}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class SiteSettingsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{5BE221A1-4BF0-491F-BD98-C53B3ABFD754}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new SiteSettings(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new SiteSettings(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/_Base Homepage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class _BaseHomepage : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.PageContent.Models.I_BaseHomepageItem {
        
        public _BaseHomepage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _BaseHomepage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Base Homepage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{782EEFC5-FEFE-45F6-B426-13F83CF04A49}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class _BaseHomepageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{782EEFC5-FEFE-45F6-B426-13F83CF04A49}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _BaseHomepage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _BaseHomepage(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/_Base Site Root template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class _BaseSiteRoot : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.PageContent.Models.I_BaseSiteRootItem {
        
        private Synthesis.FieldTypes.BooleanField _on;
        
        private Synthesis.FieldTypes.TextField _scheme;
        
        private Synthesis.FieldTypes.TextField _targetHostName;
        
        private Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField _language1;
        
        private Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField _loginPage;
        
        private Synthesis.FieldTypes.BooleanField _requireLogin;
        
        private Synthesis.FieldTypes.TextField _domain;
        
        private Synthesis.FieldTypes.BooleanField _enableWorkflow;
        
        private Synthesis.FieldTypes.BooleanField _enablePreview;
        
        private Synthesis.FieldTypes.BooleanField _allowDebug;
        
        private Synthesis.FieldTypes.TextField _browserTitle;
        
        private Synthesis.FieldTypes.DictionaryField _additionalAttributes;
        
        public _BaseSiteRoot(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _BaseSiteRoot(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Base Site Root";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{FE98FA96-B717-4D81-9F09-C7255EE07023}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the On field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("on")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField On {
            get {
                if (_on == null) {
                    _on = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3461D229-285D-495C-9919-1F4C135461A1}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "On"), this.GetSearchFieldValue("on"));
                }
                return _on;
            }
        }
        
        /// <summary>Represents the Scheme field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("scheme")]
        public Synthesis.FieldTypes.Interfaces.ITextField Scheme {
            get {
                if (_scheme == null) {
                    _scheme = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{811B6963-3E37-46B2-B7EE-99ED0ADC4359}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "Scheme"), this.GetSearchFieldValue("scheme"));
                }
                return _scheme;
            }
        }
        
        /// <summary>Represents the Target Host Name field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("target_host_name")]
        public Synthesis.FieldTypes.Interfaces.ITextField TargetHostName {
            get {
                if (_targetHostName == null) {
                    _targetHostName = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{B8B3CB32-4C04-4073-887E-4B5E11EAEC80}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "Target Host Name"), this.GetSearchFieldValue("target_host_name"));
                }
                return _targetHostName;
            }
        }
        
        /// <summary>Represents the Language field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("language")]
        public Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField Language1 {
            get {
                if (_language1 == null) {
                    _language1 = new Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{370C2996-5C2A-4B25-B062-B8FCF575DD9D}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "Language"), this.GetSearchFieldValue("language"));
                }
                return _language1;
            }
        }
        
        /// <summary>Represents the Login Page field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("login_page")]
        public Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField LoginPage {
            get {
                if (_loginPage == null) {
                    _loginPage = new Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{453EBC8B-F894-4F08-A348-20ECDE37F50F}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "Login Page"), this.GetSearchFieldValue("login_page"));
                }
                return _loginPage;
            }
        }
        
        /// <summary>Represents the Require Login field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("require_login")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField RequireLogin {
            get {
                if (_requireLogin == null) {
                    _requireLogin = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9CFF6A68-26D2-48D3-B1B7-DBDE2184C098}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "Require Login"), this.GetSearchFieldValue("require_login"));
                }
                return _requireLogin;
            }
        }
        
        /// <summary>Represents the Domain field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("domain")]
        public Synthesis.FieldTypes.Interfaces.ITextField Domain {
            get {
                if (_domain == null) {
                    _domain = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E04D9034-4D40-46EA-A63D-DD6AD65052E6}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "Domain"), this.GetSearchFieldValue("domain"));
                }
                return _domain;
            }
        }
        
        /// <summary>Represents the Enable Workflow field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("enable_workflow")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField EnableWorkflow {
            get {
                if (_enableWorkflow == null) {
                    _enableWorkflow = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{FC19D520-9E22-4FE2-A55E-45BB33FB4A6D}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "Enable Workflow"), this.GetSearchFieldValue("enable_workflow"));
                }
                return _enableWorkflow;
            }
        }
        
        /// <summary>Represents the Enable Preview field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("enable_preview")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField EnablePreview {
            get {
                if (_enablePreview == null) {
                    _enablePreview = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9EC8B9D9-29DE-4939-9757-FEB155304979}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "Enable Preview"), this.GetSearchFieldValue("enable_preview"));
                }
                return _enablePreview;
            }
        }
        
        /// <summary>Represents the Allow Debug field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("allow_debug")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField AllowDebug {
            get {
                if (_allowDebug == null) {
                    _allowDebug = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{5A1AF457-8706-4685-8545-53E632C74B0C}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "Allow Debug"), this.GetSearchFieldValue("allow_debug"));
                }
                return _allowDebug;
            }
        }
        
        /// <summary>Represents the Browser Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("browser_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField BrowserTitle {
            get {
                if (_browserTitle == null) {
                    _browserTitle = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{D21C5BEB-FF61-4F0A-99E4-019F0A429113}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "Browser Title"), this.GetSearchFieldValue("browser_title"));
                }
                return _browserTitle;
            }
        }
        
        /// <summary>Represents the Additional Attributes field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("additional_attributes")]
        public Synthesis.FieldTypes.Interfaces.IDictionaryField AdditionalAttributes {
            get {
                if (_additionalAttributes == null) {
                    _additionalAttributes = new Synthesis.FieldTypes.DictionaryField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{F80A2ADA-7D2A-4D79-B5FD-ABA251D02C5E}"], "/sitecore/templates/Feature/PageContent/_Base Site Root", "Additional Attributes"), this.GetSearchFieldValue("additional_attributes"));
                }
                return _additionalAttributes;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class _BaseSiteRootInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{FE98FA96-B717-4D81-9F09-C7255EE07023}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _BaseSiteRoot(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _BaseSiteRoot(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/PageContent/_Base Webpage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class _BaseWebpage : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.PageContent.Models.I_BaseWebpageItem {
        
        public _BaseWebpage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _BaseWebpage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Base Webpage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{09314C4F-1126-4084-9212-C98C12D5264B}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class _BaseWebpageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{09314C4F-1126-4084-9212-C98C12D5264B}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _BaseWebpage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _BaseWebpage(searchFields);
        }
    }
}
