//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Accounts.Models {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Accounts/Login Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{12D59699-84E9-416B-8539-2CC4CE25AEF3}", "Tn7CRTKtJzQZUzMEvZD34eVpXJE=", "Sitecore.Feature.Accounts")]
    public partial interface ILoginSettingsItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Forgot Password Page field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("forgot_password_page")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField ForgotPasswordPage {
            get;
        }
        
        /// <summary>Represents the Login field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("login")]
        Synthesis.FieldTypes.Interfaces.ITextField Login {
            get;
        }
        
        /// <summary>Represents the Email field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("email")]
        Synthesis.FieldTypes.Interfaces.ITextField Email {
            get;
        }
        
        /// <summary>Represents the Register Page field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("register_page")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField RegisterPage {
            get;
        }
        
        /// <summary>Represents the Email Required Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("email_required_text")]
        Synthesis.FieldTypes.Interfaces.ITextField EmailRequiredText {
            get;
        }
        
        /// <summary>Represents the Password field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("password")]
        Synthesis.FieldTypes.Interfaces.ITextField Password {
            get;
        }
        
        /// <summary>Represents the Password Required Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("password_required_text")]
        Synthesis.FieldTypes.Interfaces.ITextField PasswordRequiredText {
            get;
        }
        
        /// <summary>Represents the Forgot Password field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("forgot_password")]
        Synthesis.FieldTypes.Interfaces.ITextField ForgotPassword {
            get;
        }
        
        /// <summary>Represents the Register field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("register")]
        Synthesis.FieldTypes.Interfaces.ITextField Register {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Accounts.Models.Concrete {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Accounts/Login Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class LoginSettings : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Accounts.Models.ILoginSettingsItem {
        
        private Synthesis.FieldTypes.HyperlinkField _forgotPasswordPage;
        
        private Synthesis.FieldTypes.TextField _login;
        
        private Synthesis.FieldTypes.TextField _email;
        
        private Synthesis.FieldTypes.HyperlinkField _registerPage;
        
        private Synthesis.FieldTypes.TextField _emailRequiredText;
        
        private Synthesis.FieldTypes.TextField _password;
        
        private Synthesis.FieldTypes.TextField _passwordRequiredText;
        
        private Synthesis.FieldTypes.TextField _forgotPassword;
        
        private Synthesis.FieldTypes.TextField _register;
        
        public LoginSettings(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public LoginSettings(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Login Settings";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{12D59699-84E9-416B-8539-2CC4CE25AEF3}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Forgot Password Page field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("forgot_password_page")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField ForgotPasswordPage {
            get {
                if (_forgotPasswordPage == null) {
                    _forgotPasswordPage = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3CD76094-8F77-48DF-90C0-AA6512DEEC1C}"], "/sitecore/templates/Feature/Accounts/Login Settings", "Forgot Password Page"), this.GetSearchFieldValue("forgot_password_page"));
                }
                return _forgotPasswordPage;
            }
        }
        
        /// <summary>Represents the Login field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("login")]
        public Synthesis.FieldTypes.Interfaces.ITextField Login {
            get {
                if (_login == null) {
                    _login = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{24F05497-C417-43D1-8D4C-075C5E42B94D}"], "/sitecore/templates/Feature/Accounts/Login Settings", "Login"), this.GetSearchFieldValue("login"));
                }
                return _login;
            }
        }
        
        /// <summary>Represents the Email field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("email")]
        public Synthesis.FieldTypes.Interfaces.ITextField Email {
            get {
                if (_email == null) {
                    _email = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{8F76F7C0-33B9-4DD6-B61A-700AAE11E626}"], "/sitecore/templates/Feature/Accounts/Login Settings", "Email"), this.GetSearchFieldValue("email"));
                }
                return _email;
            }
        }
        
        /// <summary>Represents the Register Page field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("register_page")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField RegisterPage {
            get {
                if (_registerPage == null) {
                    _registerPage = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{7159D6AF-FBDA-434F-A32C-22619BA7DC66}"], "/sitecore/templates/Feature/Accounts/Login Settings", "Register Page"), this.GetSearchFieldValue("register_page"));
                }
                return _registerPage;
            }
        }
        
        /// <summary>Represents the Email Required Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("email_required_text")]
        public Synthesis.FieldTypes.Interfaces.ITextField EmailRequiredText {
            get {
                if (_emailRequiredText == null) {
                    _emailRequiredText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{F5AA0ECA-F642-4280-BE32-99E25196E78F}"], "/sitecore/templates/Feature/Accounts/Login Settings", "Email Required Text"), this.GetSearchFieldValue("email_required_text"));
                }
                return _emailRequiredText;
            }
        }
        
        /// <summary>Represents the Password field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("password")]
        public Synthesis.FieldTypes.Interfaces.ITextField Password {
            get {
                if (_password == null) {
                    _password = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{6CB8EFD4-BDA3-4D80-862F-5ADC868F9C5E}"], "/sitecore/templates/Feature/Accounts/Login Settings", "Password"), this.GetSearchFieldValue("password"));
                }
                return _password;
            }
        }
        
        /// <summary>Represents the Password Required Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("password_required_text")]
        public Synthesis.FieldTypes.Interfaces.ITextField PasswordRequiredText {
            get {
                if (_passwordRequiredText == null) {
                    _passwordRequiredText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{C9797575-73BB-4BB2-AC37-15A792597059}"], "/sitecore/templates/Feature/Accounts/Login Settings", "Password Required Text"), this.GetSearchFieldValue("password_required_text"));
                }
                return _passwordRequiredText;
            }
        }
        
        /// <summary>Represents the Forgot Password field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("forgot_password")]
        public Synthesis.FieldTypes.Interfaces.ITextField ForgotPassword {
            get {
                if (_forgotPassword == null) {
                    _forgotPassword = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{1652CCBB-3C3C-493B-BB0C-991C0BBADF89}"], "/sitecore/templates/Feature/Accounts/Login Settings", "Forgot Password"), this.GetSearchFieldValue("forgot_password"));
                }
                return _forgotPassword;
            }
        }
        
        /// <summary>Represents the Register field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("register")]
        public Synthesis.FieldTypes.Interfaces.ITextField Register {
            get {
                if (_register == null) {
                    _register = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9816E815-8B21-4B3D-83BA-24FA4DA73090}"], "/sitecore/templates/Feature/Accounts/Login Settings", "Register"), this.GetSearchFieldValue("register"));
                }
                return _register;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class LoginSettingsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{12D59699-84E9-416B-8539-2CC4CE25AEF3}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new LoginSettings(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new LoginSettings(searchFields);
        }
    }
}
