//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Project.Website.Models {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Website/Site Root template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{5FB0C585-F5AE-458B-B5B6-A031BD672F42}", "WOPRZapIeHTocOXlSGruC6zRZIk=", "Sitecore.Project.Website")]
    public partial interface ISiteRootItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Project.Website.Models.Concrete {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Website/Site Root template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class SiteRoot : global::Synthesis.StandardTemplateItem, global::Sitecore.Project.Website.Models.ISiteRootItem {
        
        public SiteRoot(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public SiteRoot(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Site Root";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{5FB0C585-F5AE-458B-B5B6-A031BD672F42}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class SiteRootInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{5FB0C585-F5AE-458B-B5B6-A031BD672F42}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new SiteRoot(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new SiteRoot(searchFields);
        }
    }
}
