//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Navigation.Models {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Link Menu template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{A06EE689-428F-4227-A728-20C7FE49F53E}", "IuSh1Z9rpz92COErZ0WkhrqLsU0=", "Sitecore.Feature.Navigation")]
    public partial interface ILinkMenuItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Additional Styles field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("additional_styles")]
        Synthesis.FieldTypes.Interfaces.ITextField AdditionalStyles {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Link Menu Item template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{EBB60F61-CC55-4107-8D70-53E347BA2B3D}", "MCCqQ9rI72s+UGh29Wqp286pvN8=", "Sitecore.Feature.Navigation")]
    public partial interface ILinkMenuItemItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Link field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField Link {
            get;
        }
        
        /// <summary>Represents the Icon field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("icon")]
        Synthesis.FieldTypes.Interfaces.ITextField Icon {
            get;
        }
        
        /// <summary>Represents the Divider Before field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("divider_before")]
        Synthesis.FieldTypes.Interfaces.IBooleanField DividerBefore {
            get;
        }
        
        /// <summary>Represents the Show Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("show_title")]
        Synthesis.FieldTypes.Interfaces.ITextField ShowTitle {
            get;
        }
        
        /// <summary>Represents the Show In Navigation Menus field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("show_in_navigation_menus")]
        Synthesis.FieldTypes.Interfaces.IBooleanField ShowInNavigationMenus {
            get;
        }
        
        /// <summary>Represents the Show Children In Menus field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("show_children_in_menus")]
        Synthesis.FieldTypes.Interfaces.IBooleanField ShowChildrenInMenus {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Navigation.Models.Concrete {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Link Menu template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class LinkMenu : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Navigation.Models.ILinkMenuItem {
        
        private Synthesis.FieldTypes.TextField _additionalStyles;
        
        public LinkMenu(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public LinkMenu(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Link Menu";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{A06EE689-428F-4227-A728-20C7FE49F53E}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Additional Styles field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("additional_styles")]
        public Synthesis.FieldTypes.Interfaces.ITextField AdditionalStyles {
            get {
                if (_additionalStyles == null) {
                    _additionalStyles = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E3BA89BD-6678-47C2-AC95-92222C91870D}"], "/sitecore/templates/Feature/Navigation/Link Menu", "Additional Styles"), this.GetSearchFieldValue("additional_styles"));
                }
                return _additionalStyles;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class LinkMenuInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{A06EE689-428F-4227-A728-20C7FE49F53E}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new LinkMenu(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new LinkMenu(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Link Menu Item template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class LinkMenuItem : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Navigation.Models.ILinkMenuItemItem {
        
        private Synthesis.FieldTypes.HyperlinkField _link;
        
        private Synthesis.FieldTypes.TextField _icon;
        
        private Synthesis.FieldTypes.BooleanField _dividerBefore;
        
        private Synthesis.FieldTypes.TextField _showTitle;
        
        private Synthesis.FieldTypes.BooleanField _showInNavigationMenus;
        
        private Synthesis.FieldTypes.BooleanField _showChildrenInMenus;
        
        public LinkMenuItem(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public LinkMenuItem(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Link Menu Item";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{EBB60F61-CC55-4107-8D70-53E347BA2B3D}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Link field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField Link {
            get {
                if (_link == null) {
                    _link = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{841FE4FB-742F-4F0D-89F0-8A372A7A399D}"], "/sitecore/templates/Feature/Navigation/Link Menu Item", "Link"), this.GetSearchFieldValue("link"));
                }
                return _link;
            }
        }
        
        /// <summary>Represents the Icon field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("icon")]
        public Synthesis.FieldTypes.Interfaces.ITextField Icon {
            get {
                if (_icon == null) {
                    _icon = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{D297FFBF-8A15-4085-A5F9-B592C0BC394E}"], "/sitecore/templates/Feature/Navigation/Link Menu Item", "Icon"), this.GetSearchFieldValue("icon"));
                }
                return _icon;
            }
        }
        
        /// <summary>Represents the Divider Before field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("divider_before")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField DividerBefore {
            get {
                if (_dividerBefore == null) {
                    _dividerBefore = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{14910048-7DCC-47E7-9123-7DDA72D039EA}"], "/sitecore/templates/Feature/Navigation/Link Menu Item", "Divider Before"), this.GetSearchFieldValue("divider_before"));
                }
                return _dividerBefore;
            }
        }
        
        /// <summary>Represents the Show Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("show_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField ShowTitle {
            get {
                if (_showTitle == null) {
                    _showTitle = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{24050942-515C-4A6E-A121-19748B526988}"], "/sitecore/templates/Feature/Navigation/Link Menu Item", "Show Title"), this.GetSearchFieldValue("show_title"));
                }
                return _showTitle;
            }
        }
        
        /// <summary>Represents the Show In Navigation Menus field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("show_in_navigation_menus")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField ShowInNavigationMenus {
            get {
                if (_showInNavigationMenus == null) {
                    _showInNavigationMenus = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{F9810CCE-C823-40E3-8E22-B65CF9510E4F}"], "/sitecore/templates/Feature/Navigation/Link Menu Item", "Show In Navigation Menus"), this.GetSearchFieldValue("show_in_navigation_menus"));
                }
                return _showInNavigationMenus;
            }
        }
        
        /// <summary>Represents the Show Children In Menus field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("show_children_in_menus")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField ShowChildrenInMenus {
            get {
                if (_showChildrenInMenus == null) {
                    _showChildrenInMenus = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{6AE6BF09-D939-4003-A851-0AE55697DC77}"], "/sitecore/templates/Feature/Navigation/Link Menu Item", "Show Children In Menus"), this.GetSearchFieldValue("show_children_in_menus"));
                }
                return _showChildrenInMenus;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class LinkMenuItemInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{EBB60F61-CC55-4107-8D70-53E347BA2B3D}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new LinkMenuItem(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new LinkMenuItem(searchFields);
        }
    }
}
