//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Navigation.Models {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Link Menu template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{A06EE689-428F-4227-A728-20C7FE49F53E}", "IuSh1Z9rpz92COErZ0WkhrqLsU0=", "Sitecore.Feature.Navigation")]
    public partial interface ILinkMenuItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Additional Styles field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("additional_styles")]
        Synthesis.FieldTypes.Interfaces.ITextField AdditionalStyles {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Link Menu Item template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{EBB60F61-CC55-4107-8D70-53E347BA2B3D}", "p1fcQ643M4OzzAari9RmYbAbofI=", "Sitecore.Feature.Navigation")]
    public partial interface ILinkMenuItemItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Link field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField Link {
            get;
        }
        
        /// <summary>Represents the Icon field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("icon")]
        Synthesis.FieldTypes.Interfaces.ITextField Icon {
            get;
        }
        
        /// <summary>Represents the Divider Before field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("divider_before")]
        Synthesis.FieldTypes.Interfaces.IBooleanField DividerBefore {
            get;
        }
        
        /// <summary>Represents the Show Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("show_title")]
        Synthesis.FieldTypes.Interfaces.ITextField ShowTitle {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Logo Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{4C291EBD-78B0-4B55-80DC-96EF86763A5F}", "kuEAVkV13rXnBUfM5YR4F/vvoBw=", "Sitecore.Feature.Navigation")]
    public partial interface ILogoSettingsItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Logo Icon field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("logo_icon")]
        Synthesis.FieldTypes.Interfaces.IImageField LogoIcon {
            get;
        }
        
        /// <summary>Represents the Link field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField Link {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Search Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{05AF8C4B-0C11-4911-B3D5-02624117AA05}", "25iDSv79na/jVGAzj9oB0iZxv/s=", "Sitecore.Feature.Navigation")]
    public partial interface ISearchSettingsItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Prompt Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("prompt_text")]
        Synthesis.FieldTypes.Interfaces.ITextField PromptText {
            get;
        }
        
        /// <summary>Represents the Search Results Page field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("search_results_page")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField SearchResultsPage {
            get;
        }
        
        /// <summary>Represents the Search field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("search")]
        Synthesis.FieldTypes.Interfaces.ITextField Search {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Navigation.Models.Concrete {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Link Menu template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class LinkMenu : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Navigation.Models.ILinkMenuItem {
        
        private Synthesis.FieldTypes.TextField _additionalStyles;
        
        public LinkMenu(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public LinkMenu(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Link Menu";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{A06EE689-428F-4227-A728-20C7FE49F53E}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Additional Styles field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("additional_styles")]
        public Synthesis.FieldTypes.Interfaces.ITextField AdditionalStyles {
            get {
                if (_additionalStyles == null) {
                    _additionalStyles = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E3BA89BD-6678-47C2-AC95-92222C91870D}"], "/sitecore/templates/Feature/Navigation/Link Menu", "Additional Styles"), this.GetSearchFieldValue("additional_styles"));
                }
                return _additionalStyles;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class LinkMenuInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{A06EE689-428F-4227-A728-20C7FE49F53E}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new LinkMenu(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new LinkMenu(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Link Menu Item template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class LinkMenuItem : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Navigation.Models.ILinkMenuItemItem {
        
        private Synthesis.FieldTypes.HyperlinkField _link;
        
        private Synthesis.FieldTypes.TextField _icon;
        
        private Synthesis.FieldTypes.BooleanField _dividerBefore;
        
        private Synthesis.FieldTypes.TextField _showTitle;
        
        public LinkMenuItem(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public LinkMenuItem(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Link Menu Item";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{EBB60F61-CC55-4107-8D70-53E347BA2B3D}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Link field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField Link {
            get {
                if (_link == null) {
                    _link = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{841FE4FB-742F-4F0D-89F0-8A372A7A399D}"], "/sitecore/templates/Feature/Navigation/Link Menu Item", "Link"), this.GetSearchFieldValue("link"));
                }
                return _link;
            }
        }
        
        /// <summary>Represents the Icon field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("icon")]
        public Synthesis.FieldTypes.Interfaces.ITextField Icon {
            get {
                if (_icon == null) {
                    _icon = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{D297FFBF-8A15-4085-A5F9-B592C0BC394E}"], "/sitecore/templates/Feature/Navigation/Link Menu Item", "Icon"), this.GetSearchFieldValue("icon"));
                }
                return _icon;
            }
        }
        
        /// <summary>Represents the Divider Before field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("divider_before")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField DividerBefore {
            get {
                if (_dividerBefore == null) {
                    _dividerBefore = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{14910048-7DCC-47E7-9123-7DDA72D039EA}"], "/sitecore/templates/Feature/Navigation/Link Menu Item", "Divider Before"), this.GetSearchFieldValue("divider_before"));
                }
                return _dividerBefore;
            }
        }
        
        /// <summary>Represents the Show Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("show_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField ShowTitle {
            get {
                if (_showTitle == null) {
                    _showTitle = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{24050942-515C-4A6E-A121-19748B526988}"], "/sitecore/templates/Feature/Navigation/Link Menu Item", "Show Title"), this.GetSearchFieldValue("show_title"));
                }
                return _showTitle;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class LinkMenuItemInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{EBB60F61-CC55-4107-8D70-53E347BA2B3D}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new LinkMenuItem(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new LinkMenuItem(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Logo Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class LogoSettings : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Navigation.Models.ILogoSettingsItem {
        
        private Synthesis.FieldTypes.ImageField _logoIcon;
        
        private Synthesis.FieldTypes.HyperlinkField _link;
        
        public LogoSettings(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public LogoSettings(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Logo Settings";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{4C291EBD-78B0-4B55-80DC-96EF86763A5F}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Logo Icon field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("logo_icon")]
        public Synthesis.FieldTypes.Interfaces.IImageField LogoIcon {
            get {
                if (_logoIcon == null) {
                    _logoIcon = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{8C0EACDF-916A-41C5-9DE4-B6BB25E9CB51}"], "/sitecore/templates/Feature/Navigation/Logo Settings", "Logo Icon"), this.GetSearchFieldValue("logo_icon"));
                }
                return _logoIcon;
            }
        }
        
        /// <summary>Represents the Link field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField Link {
            get {
                if (_link == null) {
                    _link = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{DBD7C2D3-7302-4607-95AA-466B2B32546C}"], "/sitecore/templates/Feature/Navigation/Logo Settings", "Link"), this.GetSearchFieldValue("link"));
                }
                return _link;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class LogoSettingsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{4C291EBD-78B0-4B55-80DC-96EF86763A5F}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new LogoSettings(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new LogoSettings(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Search Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class SearchSettings : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Navigation.Models.ISearchSettingsItem {
        
        private Synthesis.FieldTypes.TextField _promptText;
        
        private Synthesis.FieldTypes.HyperlinkField _searchResultsPage;
        
        private Synthesis.FieldTypes.TextField _search;
        
        public SearchSettings(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public SearchSettings(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Search Settings";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{05AF8C4B-0C11-4911-B3D5-02624117AA05}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Prompt Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("prompt_text")]
        public Synthesis.FieldTypes.Interfaces.ITextField PromptText {
            get {
                if (_promptText == null) {
                    _promptText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{FC5111E8-843E-4A36-9A57-2E77585E0CBB}"], "/sitecore/templates/Feature/Navigation/Search Settings", "Prompt Text"), this.GetSearchFieldValue("prompt_text"));
                }
                return _promptText;
            }
        }
        
        /// <summary>Represents the Search Results Page field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("search_results_page")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField SearchResultsPage {
            get {
                if (_searchResultsPage == null) {
                    _searchResultsPage = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E3C0CFE1-D7FD-4CBC-B7E6-2AA76F010F7F}"], "/sitecore/templates/Feature/Navigation/Search Settings", "Search Results Page"), this.GetSearchFieldValue("search_results_page"));
                }
                return _searchResultsPage;
            }
        }
        
        /// <summary>Represents the Search field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("search")]
        public Synthesis.FieldTypes.Interfaces.ITextField Search {
            get {
                if (_search == null) {
                    _search = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{4943C6E6-9338-4DF3-8A58-9A4A396CF435}"], "/sitecore/templates/Feature/Navigation/Search Settings", "Search"), this.GetSearchFieldValue("search"));
                }
                return _search;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class SearchSettingsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{05AF8C4B-0C11-4911-B3D5-02624117AA05}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new SearchSettings(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new SearchSettings(searchFields);
        }
    }
}
