//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Media.Models {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Media/Carousel Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{2FC223DC-20D9-4027-B20C-E1A0D67FFA07}", "6T70jJxenpzymP63vaa32iUhoeM=", "Sitecore.Feature.Media")]
    public partial interface ICarouselSettingsItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Slides field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("slides")]
        Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceListField Slides {
            get;
        }
        
        /// <summary>Represents the Active Slide field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("active_slide")]
        Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField ActiveSlide {
            get;
        }
        
        /// <summary>Represents the Transition Speed field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("transition_speed")]
        Synthesis.FieldTypes.Interfaces.IIntegerField TransitionSpeed {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Media/Carousel Slide template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{08E4A889-31B4-4479-BF74-CC4B6AB4E68F}", "01IB+P5Vmg9XrrjlmxKPRQLwUZ8=", "Sitecore.Feature.Media")]
    public partial interface ICarouselSlideItem : global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("title")]
        Synthesis.FieldTypes.Interfaces.ITextField Title {
            get;
        }
        
        /// <summary>Represents the Subtitle field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("subtitle")]
        Synthesis.FieldTypes.Interfaces.ITextField Subtitle {
            get;
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        Synthesis.FieldTypes.Interfaces.IImageField Image {
            get;
        }
        
        /// <summary>Represents the Video field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("video")]
        Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField Video {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Media.Models.Concrete {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Media/Carousel Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class CarouselSettings : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Media.Models.ICarouselSettingsItem {
        
        private Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceListField _slides;
        
        private Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField _activeSlide;
        
        private Synthesis.FieldTypes.IntegerField _transitionSpeed;
        
        public CarouselSettings(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public CarouselSettings(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Carousel Settings";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{2FC223DC-20D9-4027-B20C-E1A0D67FFA07}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Slides field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("slides")]
        public Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceListField Slides {
            get {
                if (_slides == null) {
                    _slides = new Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceListField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{1C88633E-50A6-46E7-A946-1583279B6F75}"], "/sitecore/templates/Feature/Media/Carousel Settings", "Slides"), this.GetSearchFieldValue("slides"));
                }
                return _slides;
            }
        }
        
        /// <summary>Represents the Active Slide field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("active_slide")]
        public Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField ActiveSlide {
            get {
                if (_activeSlide == null) {
                    _activeSlide = new Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{91BCEC6A-706C-480B-9EFA-87AA5E7B4A1C}"], "/sitecore/templates/Feature/Media/Carousel Settings", "Active Slide"), this.GetSearchFieldValue("active_slide"));
                }
                return _activeSlide;
            }
        }
        
        /// <summary>Represents the Transition Speed field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("transition_speed")]
        public Synthesis.FieldTypes.Interfaces.IIntegerField TransitionSpeed {
            get {
                if (_transitionSpeed == null) {
                    _transitionSpeed = new Synthesis.FieldTypes.IntegerField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{5E4B35D8-DCF1-408F-8206-D0C8F0C1B3D5}"], "/sitecore/templates/Feature/Media/Carousel Settings", "Transition Speed"), this.GetSearchFieldValue("transition_speed"));
                }
                return _transitionSpeed;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class CarouselSettingsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{2FC223DC-20D9-4027-B20C-E1A0D67FFA07}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new CarouselSettings(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new CarouselSettings(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Media/Carousel Slide template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class CarouselSlide : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Media.Models.ICarouselSlideItem {
        
        private Synthesis.FieldTypes.TextField _title;
        
        private Synthesis.FieldTypes.TextField _subtitle;
        
        private Synthesis.FieldTypes.ImageField _image;
        
        private Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField _video;
        
        public CarouselSlide(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public CarouselSlide(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Carousel Slide";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{08E4A889-31B4-4479-BF74-CC4B6AB4E68F}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Title {
            get {
                if (_title == null) {
                    _title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{837A038E-23B8-4DFD-988E-41EE01F70584}"], "/sitecore/templates/Feature/Media/Carousel Slide", "Title"), this.GetSearchFieldValue("title"));
                }
                return _title;
            }
        }
        
        /// <summary>Represents the Subtitle field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("subtitle")]
        public Synthesis.FieldTypes.Interfaces.ITextField Subtitle {
            get {
                if (_subtitle == null) {
                    _subtitle = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{F923521D-E839-4A1C-9C58-406031CEA61E}"], "/sitecore/templates/Feature/Media/Carousel Slide", "Subtitle"), this.GetSearchFieldValue("subtitle"));
                }
                return _subtitle;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image {
            get {
                if (_image == null) {
                    _image = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9F96029D-99AC-40B5-83AB-032151526829}"], "/sitecore/templates/Feature/Media/Carousel Slide", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image;
            }
        }
        
        /// <summary>Represents the Video field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("video")]
        public Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField Video {
            get {
                if (_video == null) {
                    _video = new Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{DB366C0D-B0A8-4516-8523-5002362A131C}"], "/sitecore/templates/Feature/Media/Carousel Slide", "Video"), this.GetSearchFieldValue("video"));
                }
                return _video;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class CarouselSlideInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{08E4A889-31B4-4479-BF74-CC4B6AB4E68F}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new CarouselSlide(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new CarouselSlide(searchFields);
        }
    }
}
