---
ID: "4b63f1b5-da98-4aea-a761-c5068e31b4ac"
Parent: "8c0cbc69-f633-4cd0-a863-7620b7819bb1"
Template: "8c0cbc69-f633-4cd0-a863-7620b7819bb1"
Path: /sitecore/templates/Foundation/DataAccess/_Base Standard Template/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180910T235130Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
